# Generated by Django 4.1.3 on 2022-12-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptions',
            new_name='description',
        ),
    ]
